language: c++
sudo: false
env:
  - NODE_VERSION="4"
  - NODE_VERSION="5"
  - NODE_VERSION="6"
  - NODE_VERSION="7"
  - NODE_VERSION="8"
  - NODE_VERSION="9"

before_install: null

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - npm run ci-or-install
os:
  - linux
  - osx
script:
  - npm test
  - npm run gendocs
  - npm run after-travis "Make sure to generate docs!"
after_success:
  - npm run codecov -- -f coverage/lcov.info

notifications:
  email: false
